#Porject EUler
#problem 45
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

def pent(n)

    (n*(3*n -1))/2

end

pent_list = []

1000.upto(4000) do |x|

    pent_list << pent(x)
    
end

pent_list.each do |x|
pent_list.each do |y|
    if y < x
        c = x + y
        d = x - y
    else
        break
    end
    puts x
        if pent_list.include?(d) and pent_list.include?(c)
            puts "WININEINEINER"
            puts d
            return d
        end
end
end